### ISSUE TITLE
./download folder being ignored in .gitignore

### ISSUE THREAD

**Issue by dawid-dor** [Ozpl/Python-Magic-Collection#9]
Folder **./download** (which contains JSON bulk) is missing in file structure (needs to be added manually for program to run).
Needs to be properly included/changed in **.gitignore**

**Comment by dawid-dor** [comment]
Method **build_folder_structure** from **Config** class is not being utilized - changing that will fix the issue.

**Comment by Ozpl** [comment]
Fixed in "Day 13 hotfix"
